services:
  - type: web
    name: srgpc-certificate-portal
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SRGPC_SESSION_KEY
        sync: false
      - key: SRGPC_PUBLIC_BASE_URL
        sync: false
      - key: SRGPC_ADMIN_USERNAME
        value: ADMIN
      - key: SRGPC_ADMIN_PASSWORD
        sync: false
